### PR TITLE
Decode `getblock` hex from Core (faster block decoding)

### PR DESCRIPTION
**Pull request by raffecat**
Now decodes Block HEX instead of using getrawtransaction from Core.
No longer fetches individual transactions from core.

Now fetches Block HEX from core and decodes the blocks using doge.DecodeBlock and doge.ClassifyScript in Gigawallet.

As a result, no longer needs `txindex` enabled in core config.

Gigawallet is much faster to process blocks.

### CODE REVIEW

**Comment by raffecat** [comment]
Experimental… needs some real-world testing :)
The block-decode tests pass, the script-classify tests pass.

**Comment by tjstebbing** [comment]
A good test would be reindexing giga from origin?

**Review by tjstebbing — APPROVED** [review]
great work ! This is a huge win

**Comment by qlpqlp** [comment]
I will test and reindex tomorrow and will track the time of it using my home node 🙂

**Review by qlpqlp — APPROVED** [review]
Seems really wonderful :D

**Comment by georgeartem** [comment]
That's pretty cool, does that mean we can run pruned nodes if we want?

**Comment by raffecat** [comment]
@georgeartem Yes, you can use a pruned node as long as Gigawallet has already processed the pruned blocks (typically a new install will start -100 blocks from Tip and sync from there - Giga doesn't validate blocks, it 100% trusts the Core Node to do that part)

**Pull request merged**
